name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
jobs:
  build: # make sure build/ci work properly
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
    - uses: yukiarrr/ios-build-action@v1.3.3
      with:
      p12-key-base64: ${{ secrets.SIGNING_CERTIFICATE_KEY_P12_DATA }}
      p12-cer-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
      mobileprovision-base64: ${{ secrets.PROVISIONING_PROFILE_DATA }}
      code-signing-identity: ${{ secrets.IDENTITY}}
      team-id: ${{ secrets.TEAM_ID}}
      workspace-path: SDCycleScrollView.xcworkspace # optional
